[service]
bind = "0.0.0.0"
port = 8000

[redis]
max-size = 5
min-idle = 2
max-lifetime = 30 # minutes
idle-timeout = 10 # minutes
connection-timeout = 60 # seconds

[telemetry]
otel-exporter-otlp-protocol = "grpc"
otel-service-name = "auth-service"
